# Meta Data for SEO

## Homepage
title = "LDAPCP"
titleSeparator = "-"
titleAddition = "Claims provider for ADFS authentication in SharePoint Subscription / 2019 / 2016 / 2013"
description = "LDAPCP connects SharePoint Subscription / 2019 / 2016 / 2013 with Active Directory and LDAP servers to fill the gaps and improve the experience in federated authentication."

## Documentation
# docsVersion = "0.3"

## Open Graph
#images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "www.ldapcp.com"
titleHome = "LDAPCP"

## Twitter Cards
#twitterSite = "yvand"
#twitterCreator = "yvand"

## JSON-LD
schemaType = "Organization"
schemaName = "LDAPCP"
schemaAuthor = "Yvan Duhamel"
schemaAuthorTwitter = "https://twitter.com/yvand"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/yvand/"
schemaAuthorGitHub = "https://github.com/Yvand"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/yvand"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/Yvand/LDAPCP"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Site built with <a href=\"https://gohugo.io/\" class=\"gdoc-footer__link\" target=\"_blank\">Hugo</a> and <a class=\"gdoc-footer__link\" href=\"https://getdoks.org/\" target=\"_blank\">Doks</a>. Project developed and maintained with ❤️ by <a href=\"https://www.linkedin.com/in/yvand/\" class=\"gdoc-footer__link\" target=\"_blank\">Yvan Duhamel</a>."

# Feed
copyRight = "Copyright (c) 2020-2022 Yvan Duhamel"

# Alert
alert = false
alertDismissable = true
alertText = "Like LDAPCP? <a class=\"alert-link\" href=\"https://github.com/Yvand/LDAPCP/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
docsRepo = "https://github.com/Yvand/hugo-LDAPCP"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = true

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = false
