# Meta Data for SEO

## Homepage
title = "LDAPCP"
titleSeparator = "-"
titleAddition = "Claims provider for SharePoint 2019 / 2016 / 2013"
description = "This claims provider connects SharePoint 2019 / 2016 / 2013 with Active Directory and LDAP servers to enhance people picker with a great search experience in federated authentication (typically ADFS)"

## Open Graph + Twitter Cards
#images = ["doks.png"]
#twitterSite = "henkverlinde"
#twitterCreator = "henkverlinde"
#facebookAuthor = "verlinde.henk"
#facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
#schemaType = "Organization"
#schemaLogo = "logo-doks.png"
#schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/yvand/"
schemaGitHub = "https://github.com/Yvand"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
# footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"
footer = "Site built with <a href=\"https://gohugo.io/\" class=\"gdoc-footer__link\">Hugo</a>. Project developed and maintained with <svg width=\"20\" height=\"20\" viewBox=\"-2.29 -2.29 36.57 36.57\" id=\"gdoc_heart\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16 29.714a1.11 1.11 0 01-.786-.321L4.072 18.643c-.143-.125-4.071-3.714-4.071-8 0-5.232 3.196-8.357 8.535-8.357 3.125 0 6.053 2.464 7.464 3.857 1.411-1.393 4.339-3.857 7.464-3.857 5.339 0 8.535 3.125 8.535 8.357 0 4.286-3.928 7.875-4.089 8.035L16.785 29.392c-.214.214-.5.321-.786.321z\"/></svg> by <a href=\"https://www.linkedin.com/in/yvand/\" class=\"gdoc-footer__link\">Yvan Duhamel</a>."

# Alert
alert = false
# alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/Yvand/hugo-LDAPCP"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
